### ISSUE TITLE
Question / Problem : Table creation

### ISSUE THREAD

**Issue by hepaestus** [GoogleCloudPlatform/appengine-django-skeleton#19]
The commands in the Deploy section of the README don't seem to create the database tables on the google cloud. What else is required to get the installation up an running? How do I get the tables created on the app engine? 
Thanks,
Pete.

**Comment by NitraxHub** [comment]
What happens when you run 
`python manage.py migrate` ?

you could also try to use
`python manage.py makemigrations`
first, and then try the migrate again.


More information about Django Migrations [here](https://docs.djangoproject.com/en/1.9/topics/migrations/)

**Comment by hepaestus** [comment]
Those create the tables locally but not on the remote DB. :P
Pete.

**Comment by NitraxHub** [comment]
Aha.

Check out this link for how to set it up to connect to the Cloud SQL from local development
https://cloud.google.com/appengine/docs/python/cloud-sql/django#running-the-development-server

Spesifically under the "Alternate development database and settings" section.

**Comment by hepaestus** [comment]
Still no love on my end. None of that stuff helped or was relevant. There is no clear way to get from step 4 to step 5 of the deploy section.

**Comment by waprin** [comment]
Sorry you haven't gotten it working yet.

The idea in the docs is that you use the remote CloudSQL database both locally and when you deploy.  You may or may not want to do this but that's how the instructions are written. That means when you run the migrations, you are running them on the actual CloudSQL database. 

Connecting to that database is differently locally or on App Engine. On App Engine, it's the unix socket. Locally, you open up connections from the outside and then connect via a usual host/port/database/user/password combination.

README for this repo absolutely needs improvement. Let me know if the above makes sense/where you're stuck and once we fix the issue you can give me some tips on how the doc could be more clear.
