### ISSUE TITLE
OperationalError at /admin/login/

### ISSUE THREAD

**Issue by EssaAlshammri** [GoogleCloudPlatform/appengine-django-skeleton#25]
```(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 38")```

this happens on production 
but when I run it on my local host it connects to the mysql server just fine

**Comment by jonparrott** [comment]
@EssaAlshammri can you share your app.yaml with us? Feel free to elide any passwords. Are you using Cloud SQL? First generation or second generation?

@waprin any ideas?

**Comment by EssaAlshammri** [comment]
@jonparrott 
It was first generation 
the problem was I can't give an authorization to my app from sql instances when it's on a different region
all I did is creating another database with the same region as my project and it worked
it's solved now :)
thanks for the replay
