### ISSUE TITLE
ImportError: No module named django.core.management when running manage.py

### ISSUE THREAD

**Issue by NitraxHub** [GoogleCloudPlatform/appengine-django-skeleton#9]
Hey!
So when I create a new project, I follow the direction as best I can, but still I've come across this error every time I run manage.py using this skeleton.

> ImportError: No module named django.core.management when running manage.py 

However, I only need to add the line
`sys.path.append('lib')`
in the manage.py to make it work as intended. 

Just wanted to point this out, and maybe check if any of you know of a better way to get around this?

Thanks

Also, in the documentation it says 'Django 1.8' is the version being used, but in the project 1.9 is the one included, maybe this should be updated  to reflect this?

**Comment by waprin** [comment]
Thanks for the report, I agree I missed documenting that step, take a look at the PR I just created and let me know if you think it's sufficient now.

**Comment by NitraxHub** [comment]
Cool, looks good. Thank you.
